src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $display_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function isGranted($role): bool
    {
        return in_array($role, $this->getRoles());
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use App\Service\Menus;

use Doctrine\ORM\EntityManagerInterface;


Class HomeController extends AbstractController
{
    public function index(){
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $menus = new Menus();
        return $this->render('main.html.twig', [
            "menus" => $menus->getMenus( $this->getUser() )
        ]);
    }

}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use App\Entity\User;
use App\Service\Menus;
use Doctrine\ORM\EntityManagerInterface;


class SecurityController extends AbstractController
{

    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    public function logout()
    {
        throw new \Exception('This method can be blank - it will be intercepted by the logout key on your firewall');
    }

    public function showRegisterForm()
    {
        return $this->render('security/register.html.twig', [
            'form' => $this->getRegisterForm()->createView()
        ]);
    }

    private function getRegisterForm()
    {
        return $this->createFormBuilder()
        ->add('email', EmailType::class,[])
        ->add('password', PasswordType::class, [])
        ->add('display_name', TextType::class,[])
        ->add('save', SubmitType::class,[])
        ->getForm();

    }

    public function getNbUsersActives() {

        $em = $this->getDoctrine()->getManager();
        $repoUser = $em->getRepository(User::class);
 
        $totalUsers = $repoUser->createQueryBuilder('u')
            ->select('count(u.id)')
            ->where('u.active= 1')
            ->getQuery()
            ->getSingleScalarResult();
        return $totalUsers;
    }

    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $form =  $this->getRegisterForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $data = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $user = new User();
            $user   ->setEmail($data["email"])
                    ->setPassword( $passwordEncoder->encodePassword($user,$data["password"])   )
                    ->setDisplayName( $data["display_name"] );

            if( $this->getNbUsersActives() == 0 )
            {
                //it's the first user, he will be activated and added to group SUPER_ADMIN
                $user->setActive(true)
                     ->setRoles( array('SUPER_ADMIN'));
            }else{
                $user->setActive(false);
            }

            $entityManager->persist($user);
            $entityManager->flush();
            return $this->redirectToRoute('index',[]);
        }

    }
    private function getformCreateUser()
    {
        return $this->createFormBuilder()
        ->add('email', EmailType::class,[])
        ->add('password', PasswordType::class, [])
        ->add('display_name', TextType::class,[])
        ->add('roles', ChoiceType::class, [
            'choices'  => [
                'USER' => false,
                'RESOURCE_MANAGER' => 'RESOURCE_MANAGER',
                'SUPER ADMIN' => 'SUPER_ADMIN',
                ],
            'multiple'  => false
            ])
        ->add('save', SubmitType::class,[])
        ->getForm();
    }
    
    public function showUserManagePage(Request $request,  UserPasswordEncoderInterface $passwordEncoder)
    {


        $formCreateUser = $this->getformCreateUser();
        $formCreateUser->handleRequest($request);

        if ($formCreateUser->isSubmitted() && $formCreateUser->isValid()) {
            $userValues = $formCreateUser->getData();
            
            $user = new User();
            $user   ->setEmail($userValues ["email"])
                    ->setPassword( $passwordEncoder->encodePassword($user,$userValues ["password"])   )
                    ->setDisplayName( $userValues ["display_name"] )
                    ->setActive(true)
                    ->setRoles(array( $userValues["roles"] ));

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            //empty the form
            $formCreateUser = $this->getformCreateUser();

        }

        $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->findAll();
        $menus = new Menus();


        return $this->render('security/listUsers.html.twig', [
            "menus" => $menus->getMenus( $this->getUser() ),
            "users" => $users,
            "formCreateUser"  => $formCreateUser->createView()
        ]);
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>{% block title %}Resources manager{% endblock %}</title>
        {% block stylesheets %}
        <link href="{{ asset('/css/style.css') }}" type="text/css" rel="stylesheet" />
        {% endblock %}
    </head>
    <body>
        <header>{% block header %}<h1>Resources booking manager</h1>{% endblock %}</header>
        <nav>{% block nav %}{% endblock %}</nav>
        {% block overcontent %}
        <section id="main">
        {% block content %}{% include 'menu.html.twig' %}{% endblock %}
        </section>
        {% endblock %}
        <footer></footer>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/main.html.twig
{% extends 'base.html.twig' %}

{% block header %}<h1>Gestionnaire de ressources</h1>{% endblock %}

{% block title %}Page d'accueil{% endblock %}
{% block nav %}{% include 'menus.html.twig' %}{% endblock %}

{% block content %}Hey hey!{% endblock %}

templates/menus.html.twig
<ul>
{% for m in menus %}
<li>
    <a href="{{ path(m.route) }}">{{ m.title }}</a>
</li>
{% endfor %}
</ul>

templates/security/listUsers.html.twig
{% extends 'base.html.twig' %}
{% block title %}Manage users{% endblock %}
{% block header %}<h1>Manage users</h1>{% endblock %}
{% block nav %}{% include 'menus.html.twig' %}{% endblock %}
{% block content %}

<article id="FormCreateUser">
        <h2>Create a new user</h2>
        {{ form(formCreateUser) }}
        <p>{{ form_errors(formCreateUser) }}</p>
</article>

<article>
    <h2>Users list</h2>
    <table>
        <thead>
            <tr>
                <th>Displayed Name</th>
                <th>Login (email)</th>
                <th>Roles</th>
                <th>Active</th>
            </tr>
        </thead>
        <tbody>
        {% for u in users %}
            <tr>
                <td>{{ u.displayName }} </td>
                <td>{{ u.email }}</td>
                <td>{{ u.roles|join(',')  }}</td>
                <td>{{ u.active? 'Yes':'No' }}</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
</article>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in{% endblock %}

{% block overcontent %}
<section class="overnav">
    <form method="post">
        <h2>Please sign in</h2>
        <label for="inputEmail">Email</label> <input type="email" value="{{ last_username }}" name="email" id="inputEmail" required autofocus>
        <label for="inputPassword">Password</label> <input type="password" name="password" id="inputPassword" required>
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}"/>
        <input type="submit" value="Sign in"/>
    </form>
</section>
{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}
{% block title %}Register{% endblock %}
{% block header %}<h1>Register a new user</h1>{% endblock %}
{% block overcontent %}
<section class="overnav">
{{ form(form) }}
</section>
{% endblock %}